Add libcore src to the dx docs module.
This fixed bogus docs build errors like:
dalvik/dx/src/com/android/dx/io/DexIndexPrinter.java:19: error: package
com.android.dex does not exist

Change-Id: I3217a51c1562194974410c54f936c0713455a93c